#Nombre del workflow
name: CI

#Eventos en los que se ejecutara.
on:
  push:
    branches: [ "main" ]
  #Ejecutar un workflow manualmente
  workflow_dispatch:

#Pasos del programas
jobs:

  build:
    #Ejecutaremos una maquina de ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: 'Mostrar mensaje'
        run: echo 'Hola mundo'
      
