name: Asignar el pull requests a un usuario
run-name: workflow iniciado por @${{ github.actor }}

on:
  push:
    branches:
      - testing  

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Configurar el repositorio
      - name: Verficar Codigo
        uses: actions/checkout@v4

      # Paso 2: Crear un Pull Request si no existe
      - name: Creación del Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: testing
          title: "Automatización del Pull Request - testing"
          body: |
            Jean revisa esto pe.
          reviewers: jemjaf

      
