name: Asignar el pull requests a un usuario
run-name: workflow iniciado por @${{ github.actor }}

on:
  push:
    branches:
      - testing  

permissions:
  contents: write  # Permite que el bot haga push y otras acciones de escritura en el repositorio}
  pull-requests: write

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Configurar el repositorio
      - name: Verficar Codigo
        uses: actions/checkout@v4

      # Paso 2: Crear un Pull Request si no existe
      - name: Creaci칩n del Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main
          title: "Automatizaci칩n del Pull Request - testing"
          body: |
            Jean revisa esto pe.
          reviewers: jemjaf

      # Paso 3: A침adir comentarios autom치ticos al Pull Request
      - name: Comentar el Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `testing`
            });

            if (pullRequests.length > 0) {
              const prNumber = pullRequests[0].number;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: "Veamos donde va esto."
              });
            }

      
