name: PR Comment with OpenAI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read  
  pull-requests: write  

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install openai 
          pip install PyGithub

      - name: Generate PR review with OpenAI
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
            run: |
            python - <<EOF
            import os
            from github import Github

            # Configuración del cliente de GitHub
            token = os.getenv("MY_TOKEN")
            repo_name = os.getenv("GITHUB_REPOSITORY")
            pr_number = int(os.getenv("PR_NUMBER"))

            g = Github(token)
            repo = g.get_repo(repo_name)
            pr = repo.get_pull(pr_number)

            # Obtener los archivos cambiados
            files = pr.get_files()
            changed_files = [file.filename for file in files]

            # Generar comentario
            comment = f"Los archivos modificados en este PR son:\n" + "\n".join(changed_files)

            # Publicar el comentario
            pr.create_issue_comment(comment)
            print("Comentario publicado exitosamente.")
            EOF
          
      
