name: Probando la API de Chat gpt
run-name: ${{ github.actor }} está ejecutando este workflow

on:
  pull_request:
    types: opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install openai

      - name: Ejecución del programa
        run: |
          python pr_review.py
      
